import { getCollections } from "./mongodb";
import {
  findClusterMembers,
  evaluateAutoFaqTrigger,
  AUTO_FAQ_WINDOW_HOURS,
} from "./similarity";
import { draftFaqEntry } from "./gemini";
import { deriveRiskLevel } from "./risk";

// Auto-FAQ generation from repeated queries.
//
// Rule: when a topic accounts for a majority share of everyone using the app
// in a rolling window — "5 of the 10 people who asked anything today asked
// about dengue" — that topic is going around, and Vitaura publishes a FAQ
// entry for it so the next person finds an answer without having to ask.
//
// Share is the signal, but share alone is unusable at low traffic (one user is
// 100% of one user), so a minimum headcount gates it. See
// evaluateAutoFaqTrigger in lib/similarity.js. Both numbers are env-tunable.
//
// "Same topic" is cosine similarity over the claim embeddings we already
// compute for retrieval — no second model, no extra storage.
//
// On what counts as a "user": Vitaura has no login on the user side (by
// design — zero friction), so there is no account identity to dedupe on. We
// approximate a distinct person as a distinct sessionId — a random id the
// frontend generates once and keeps in localStorage. A claim with no
// sessionId counts as its own distinct person, which is the safe direction:
// it can only ever grow the denominator, never shrink it, so an unidentified
// claim cannot inflate a topic's share and trigger a spurious publish.
export async function maybeCreateAutoFaq({ newClaimDoc }) {
  try {
    const { claims, faqPosts } = await getCollections();

    const windowStart = new Date(Date.now() - AUTO_FAQ_WINDOW_HOURS * 60 * 60 * 1000);
    const recentClaims = await claims
      .find({ createdAt: { $gte: windowStart }, embedding: { $exists: true } })
      .project({
        _id: 1,
        text: 1,
        claim: 1,
        sessionId: 1,
        embedding: 1,
        verdict: 1,
        explanation: 1,
        language: 1,
        actionRisk: 1,
        evidenceConfidence: 1,
        sourceCitation: 1,
        topicTags: 1,
      })
      .limit(500)
      .toArray();

    // Identify a "person" consistently for both numerator and denominator.
    // Claims with no sessionId each count as their own distinct person, so a
    // missing id can never silently deflate the denominator and inflate the
    // share.
    const identify = (claim) => claim.sessionId || `no-session-${claim._id}`;

    const members = findClusterMembers(newClaimDoc.embedding, recentClaims);
    const clusterSessions = new Set(members.map(identify));
    // Denominator: everyone who checked ANYTHING in the window, not just this
    // topic — that's what makes the number a share rather than a count.
    const totalSessions = new Set(recentClaims.map(identify));

    const trigger = evaluateAutoFaqTrigger(clusterSessions.size, totalSessions.size);
    if (!trigger.publish) return null;

    // Stable identity for this cluster: the id of its oldest member. As the
    // cluster grows, newer claims join it but the oldest one doesn't change,
    // so two checks crossing the threshold concurrently derive the same key
    // and the upsert below collapses them into one post instead of publishing
    // the same FAQ twice.
    const clusterKey = members
      .map((m) => m._id.toString())
      .sort()[0];

    const existing = await faqPosts.findOne({ clusterKey });
    if (existing) {
      // Already published — keep the "N of M people asked" figures honest as
      // the cluster keeps growing, so the admin table doesn't show the stale
      // numbers from the moment it first fired.
      await faqPosts.updateOne(
        { _id: existing._id },
        {
          $set: {
            clusterSize: clusterSessions.size,
            clusterTotalSessions: totalSessions.size,
            clusterShare: trigger.share,
            sourceClaimIds: members.map((m) => m._id),
            updatedAt: new Date(),
          },
        }
      );
      return null;
    }

    // Draft the public entry from the verdict this claim already received.
    // The verdict is NOT recomputed here — it was decided by a source-grounded
    // check, and re-deciding it risks publishing a different answer than the
    // one the user was shown.
    const drafted = await draftFaqEntry({
      claimText: newClaimDoc.claim || newClaimDoc.text,
      verdict: newClaimDoc.verdict,
      explanation: newClaimDoc.explanation,
      sourceTitle: newClaimDoc.sourceCitation?.title || null,
      language: newClaimDoc.language,
    });

    const doc = {
      title: drafted.title,
      body: drafted.body,
      sourceLink: newClaimDoc.sourceCitation?.url || null,
      topicTag: newClaimDoc.topicTags?.[0] || drafted.topicTag,
      isAutoGenerated: true,
      // "Trending now" on the homepage reads posts with isAutoGenerated or
      // featured. This is the real signal: a majority of everyone who used the
      // app today asked about this one thing — a live proxy for "this is going
      // viral" that needs no external social-media API.
      verdict: newClaimDoc.verdict,
      riskLevel:
        newClaimDoc.riskLevel || deriveRiskLevel(newClaimDoc.verdict, newClaimDoc.actionRisk),
      evidenceConfidence: newClaimDoc.evidenceConfidence ?? null,
      actionRisk: newClaimDoc.actionRisk ?? null,
      clusterKey,
      clusterSize: clusterSessions.size,
      // Persisted so the admin FAQ table can show why this published —
      // "5 of 10 people (50%)" — rather than an unexplained count.
      clusterTotalSessions: totalSessions.size,
      clusterShare: trigger.share,
      exampleText: (newClaimDoc.text || "").slice(0, 300),
      sourceClaimIds: members.map((m) => m._id),
      createdAt: new Date(),
      createdBy: "system",
    };

    // Upsert-on-clusterKey rather than insertOne, so a concurrent run that got
    // past the findOne above can't create a duplicate. The guarantee comes
    // from the partial unique index on clusterKey (lib/indexes.js) — without
    // it this is just a smaller race window, not a closed one.
    let result;
    try {
      result = await faqPosts.updateOne(
        { clusterKey },
        { $setOnInsert: doc },
        { upsert: true }
      );
    } catch (err) {
      // 11000 = duplicate key. The index did its job: another run inserted
      // this cluster's post between our findOne and this upsert. That's the
      // dedupe working, not a failure, so it must not be logged as an error.
      if (err?.code === 11000) return null;
      throw err;
    }
    if (!result.upsertedId) return null; // matched an existing post; nothing to do

    console.log(
      `[autoFaq] published auto-FAQ for cluster ${clusterKey}: ${trigger.reason}`
    );
    return { _id: result.upsertedId, ...doc };
  } catch (err) {
    // Auto-FAQ is a bonus feature — never let it break the main check flow.
    console.error("[autoFaq] failed:", err);
    return null;
  }
}
