import { getCollections } from "./mongodb";
import {
  findClusterMembers,
  AUTO_FAQ_USER_COUNT_THRESHOLD,
  AUTO_FAQ_WINDOW_HOURS,
} from "./similarity";
import { checkClaim, verdictToRiskLevel } from "./gemini";

// Simplification note: the spec's threshold is "5+ distinct users." Vitaura
// has no login/user accounts on the user side (by design — zero friction),
// so there's no real user identity to dedupe on. We approximate "distinct
// users" as "distinct sessionId values" (a random id the frontend generates
// once and stores in localStorage) attached to each claim. If a claim has
// no sessionId, it counts as its own distinct session.
export async function maybeCreateAutoFaq({ newClaimDoc }) {
  try {
    const { claims, faqPosts } = await getCollections();

    const windowStart = new Date(Date.now() - AUTO_FAQ_WINDOW_HOURS * 60 * 60 * 1000);
    const recentClaims = await claims
      .find({ createdAt: { $gte: windowStart }, embedding: { $exists: true } })
      .project({ _id: 1, text: 1, sessionId: 1, embedding: 1, verdict: 1, sourceCitation: 1 })
      .limit(500)
      .toArray();

    const members = findClusterMembers(newClaimDoc.embedding, recentClaims);
    const distinctSessions = new Set(
      members.map((m) => m.sessionId || `no-session-${m._id}`)
    );

    if (distinctSessions.size < AUTO_FAQ_USER_COUNT_THRESHOLD) {
      return null; // cluster hasn't crossed the threshold yet
    }

    // Avoid duplicate auto-FAQ posts for the same cluster: skip if an
    // auto-generated post already exists citing one of these claim ids.
    const memberIds = members.map((m) => m._id);
    const existing = await faqPosts.findOne({
      isAutoGenerated: true,
      sourceClaimIds: { $in: memberIds },
    });
    if (existing) return null;

    // Draft the FAQ post via Gemini, grounded in the cluster's own claim +
    // verdict (already source-backed from the original check).
    const summary = await checkClaim({
      rawMessage: `Multiple users (${distinctSessions.size}) have asked about this same claim recently: "${newClaimDoc.text}". Write a short public FAQ entry (title + body) summarizing the claim and the verdict: ${newClaimDoc.verdict}. Explanation to build on: ${newClaimDoc.explanation}`,
      language: newClaimDoc.language,
      sources: newClaimDoc.sourceCitation
        ? [{ title: newClaimDoc.sourceCitation.title, url: newClaimDoc.sourceCitation.url, text: newClaimDoc.explanation }]
        : [],
    });

    const doc = {
      title: summary.claim.slice(0, 140),
      body: summary.explanation,
      sourceLink: newClaimDoc.sourceCitation?.url || null,
      topicTag: newClaimDoc.sourceCitation?.title || "general",
      isAutoGenerated: true,
      // "Trending now" homepage feed reads posts with isAutoGenerated or
      // featured — this is the real signal: N distinct people asked about
      // the same thing within a day, so it's a live proxy for "going viral"
      // that needs no external social-media API.
      verdict: newClaimDoc.verdict,
      riskLevel: newClaimDoc.riskLevel || verdictToRiskLevel(newClaimDoc.verdict),
      evidenceConfidence: newClaimDoc.evidenceConfidence ?? null,
      actionRisk: newClaimDoc.actionRisk ?? null,
      clusterSize: distinctSessions.size,
      exampleText: newClaimDoc.text.slice(0, 300),
      sourceClaimIds: memberIds,
      createdAt: new Date(),
      createdBy: "system",
    };
    const result = await faqPosts.insertOne(doc);
    return { _id: result.insertedId, ...doc };
  } catch (err) {
    // Auto-FAQ is a bonus feature — never let it break the main check flow.
    console.error("[autoFaq] failed:", err);
    return null;
  }
}
