import { getCollections } from "./mongodb";
import {
  findClusterMembers,
  AUTO_FAQ_USER_COUNT_THRESHOLD,
  AUTO_FAQ_WINDOW_HOURS,
} from "./similarity";
import { draftFaqEntry } from "./gemini";
import { deriveRiskLevel } from "./risk";

// Auto-FAQ generation from repeated queries.
//
// Rule: when N distinct people ask about the same topic inside a rolling
// window, that topic is going around, and Vitaura publishes a FAQ entry for it
// so the next person finds an answer without having to ask at all.
//
// "Same topic" is cosine similarity over the claim embeddings we already
// compute for retrieval — no second model, no extra storage.
//
// Simplification note: the spec's threshold is "5+ distinct users." Vitaura
// has no login/user accounts on the user side (by design — zero friction), so
// there's no real user identity to dedupe on. We approximate "distinct users"
// as "distinct sessionId values" (a random id the frontend generates once and
// stores in localStorage). A claim with no sessionId counts as its own
// distinct session. Both thresholds are env-tunable — see lib/similarity.js.
export async function maybeCreateAutoFaq({ newClaimDoc }) {
  try {
    const { claims, faqPosts } = await getCollections();

    const windowStart = new Date(Date.now() - AUTO_FAQ_WINDOW_HOURS * 60 * 60 * 1000);
    const recentClaims = await claims
      .find({ createdAt: { $gte: windowStart }, embedding: { $exists: true } })
      .project({
        _id: 1,
        text: 1,
        claim: 1,
        sessionId: 1,
        embedding: 1,
        verdict: 1,
        explanation: 1,
        language: 1,
        actionRisk: 1,
        evidenceConfidence: 1,
        sourceCitation: 1,
        topicTags: 1,
      })
      .limit(500)
      .toArray();

    const members = findClusterMembers(newClaimDoc.embedding, recentClaims);
    const distinctSessions = new Set(
      members.map((m) => m.sessionId || `no-session-${m._id}`)
    );

    if (distinctSessions.size < AUTO_FAQ_USER_COUNT_THRESHOLD) {
      return null; // cluster hasn't crossed the threshold yet
    }

    // Stable identity for this cluster: the id of its oldest member. As the
    // cluster grows, newer claims join it but the oldest one doesn't change,
    // so two checks crossing the threshold concurrently derive the same key
    // and the upsert below collapses them into one post instead of publishing
    // the same FAQ twice.
    const clusterKey = members
      .map((m) => m._id.toString())
      .sort()[0];

    const existing = await faqPosts.findOne({ clusterKey });
    if (existing) {
      // Already published — just keep the "N people asked" counter honest.
      await faqPosts.updateOne(
        { _id: existing._id },
        {
          $set: {
            clusterSize: distinctSessions.size,
            sourceClaimIds: members.map((m) => m._id),
            updatedAt: new Date(),
          },
        }
      );
      return null;
    }

    // Draft the public entry from the verdict this claim already received.
    // The verdict is NOT recomputed here — it was decided by a source-grounded
    // check, and re-deciding it risks publishing a different answer than the
    // one the user was shown.
    const drafted = await draftFaqEntry({
      claimText: newClaimDoc.claim || newClaimDoc.text,
      verdict: newClaimDoc.verdict,
      explanation: newClaimDoc.explanation,
      sourceTitle: newClaimDoc.sourceCitation?.title || null,
      language: newClaimDoc.language,
    });

    const doc = {
      title: drafted.title,
      body: drafted.body,
      sourceLink: newClaimDoc.sourceCitation?.url || null,
      topicTag: newClaimDoc.topicTags?.[0] || drafted.topicTag,
      isAutoGenerated: true,
      // "Trending now" on the homepage reads posts with isAutoGenerated or
      // featured. This is the real signal: N distinct people asked about the
      // same thing within a day — a live proxy for "this is going viral" that
      // needs no external social-media API.
      verdict: newClaimDoc.verdict,
      riskLevel:
        newClaimDoc.riskLevel || deriveRiskLevel(newClaimDoc.verdict, newClaimDoc.actionRisk),
      evidenceConfidence: newClaimDoc.evidenceConfidence ?? null,
      actionRisk: newClaimDoc.actionRisk ?? null,
      clusterKey,
      clusterSize: distinctSessions.size,
      exampleText: (newClaimDoc.text || "").slice(0, 300),
      sourceClaimIds: members.map((m) => m._id),
      createdAt: new Date(),
      createdBy: "system",
    };

    // Upsert-on-clusterKey rather than insertOne, so a concurrent run that got
    // past the findOne above can't create a duplicate. The guarantee comes
    // from the partial unique index on clusterKey (lib/indexes.js) — without
    // it this is just a smaller race window, not a closed one.
    let result;
    try {
      result = await faqPosts.updateOne(
        { clusterKey },
        { $setOnInsert: doc },
        { upsert: true }
      );
    } catch (err) {
      // 11000 = duplicate key. The index did its job: another run inserted
      // this cluster's post between our findOne and this upsert. That's the
      // dedupe working, not a failure, so it must not be logged as an error.
      if (err?.code === 11000) return null;
      throw err;
    }
    if (!result.upsertedId) return null; // matched an existing post; nothing to do

    console.log(
      `[autoFaq] published auto-FAQ for cluster ${clusterKey} (${distinctSessions.size} distinct sessions)`
    );
    return { _id: result.upsertedId, ...doc };
  } catch (err) {
    // Auto-FAQ is a bonus feature — never let it break the main check flow.
    console.error("[autoFaq] failed:", err);
    return null;
  }
}
