"use client";

import { Suspense, useEffect, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Logo } from "@/components/Logo";
import { Card } from "@/components/Card";
import { VerdictBadge } from "@/components/StatusBadge";

export default function FaqPage() {
  return (
    // useSearchParams needs a Suspense boundary — lets a trending card on
    // the homepage deep-link here as /faq?q=<topic> and land pre-filtered.
    <Suspense fallback={null}>
      <FaqPageInner />
    </Suspense>
  );
}

function FaqPageInner() {
  const searchParams = useSearchParams();
  const [posts, setPosts] = useState([]);
  const [query, setQuery] = useState(searchParams.get("q") || "");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const controller = new AbortController();
    // Intentional: reset loading before each (re-)fetch triggered by `query` changing.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setLoading(true);
    fetch(`/api/faq${query ? `?q=${encodeURIComponent(query)}` : ""}`, {
      signal: controller.signal,
    })
      .then((res) => res.json())
      .then((data) => setPosts(Array.isArray(data) ? data : []))
      .catch(() => {})
      .finally(() => setLoading(false));
    return () => controller.abort();
  }, [query]);

  return (
    <main className="mx-auto max-w-md px-5 pt-8 pb-16">
      <Link href="/">
        <Logo className="mb-8" />
      </Link>

      <h1 className="font-display text-xl font-semibold mb-1">Health FAQs</h1>
      <p className="text-sm mb-5" style={{ color: "var(--muted)" }}>
        Claims verified so often we&apos;ve turned them into quick answers.
      </p>

      <input
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        placeholder="Search topics…"
        className="w-full rounded-full border border-border bg-transparent px-4 py-3 text-sm mb-5 outline-none focus:border-accent"
      />

      {loading && (
        <p className="text-sm" style={{ color: "var(--muted)" }}>
          Loading…
        </p>
      )}

      {!loading && posts.length === 0 && (
        <p className="text-sm" style={{ color: "var(--muted)" }}>
          No FAQ entries yet — check back soon.
        </p>
      )}

      <div className="flex flex-col gap-3">
        {posts.map((post) => (
          <Card key={post.id}>
            <div className="flex items-start justify-between gap-2 mb-2">
              <p className="text-sm font-semibold leading-snug">{post.title}</p>
              <div className="flex items-center gap-1 shrink-0">
                {post.verdict && <VerdictBadge verdict={post.verdict} />}
                {post.isAutoGenerated && (
                  <span
                    className="label-tracked text-[9px] rounded-full px-2 py-0.5"
                    style={{ background: "var(--accent-soft)", color: "var(--accent)" }}
                  >
                    Auto
                  </span>
                )}
              </div>
            </div>
            <p className="text-xs leading-relaxed mb-2" style={{ color: "var(--muted)" }}>
              {post.body}
            </p>
            <div className="flex items-center justify-between text-[11px]" style={{ color: "var(--muted)" }}>
              <span>{post.topicTag}</span>
              {post.sourceLink && (
                <a href={post.sourceLink} target="_blank" rel="noreferrer" style={{ color: "var(--accent)" }}>
                  Source ↗
                </a>
              )}
            </div>
          </Card>
        ))}
      </div>
    </main>
  );
}
