"use client";

import { useCallback, useEffect, useState } from "react";
import { Card, PillButton, SectionLabel } from "@/components/Card";
import { VerdictBadge } from "@/components/StatusBadge";

const EMPTY_FORM = {
  title: "",
  body: "",
  sourceLink: "",
  topicTag: "",
  featured: false,
  unpublished: false,
  verdict: "",
};
const VERDICTS = ["true", "false", "misleading", "unverified"];
const FILTERS = [
  { key: "all", label: "All" },
  { key: "auto", label: "Auto-generated" },
  { key: "manual", label: "Written by admin" },
  { key: "hidden", label: "Unpublished" },
];

export default function AdminFaqPage() {
  const [posts, setPosts] = useState(null);
  const [error, setError] = useState("");
  const [form, setForm] = useState(EMPTY_FORM);
  const [editingId, setEditingId] = useState(null);
  const [saving, setSaving] = useState(false);
  const [formError, setFormError] = useState("");
  const [filter, setFilter] = useState("all");

  const load = useCallback(() => {
    fetch("/api/admin/faq")
      .then((res) => (res.ok ? res.json() : Promise.reject()))
      .then(setPosts)
      .catch(() => setError("Couldn't load FAQ posts."));
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  function startEdit(p) {
    setEditingId(p.id);
    setForm({
      title: p.title,
      body: p.body,
      sourceLink: p.sourceLink || "",
      topicTag: p.topicTag || "",
      featured: !!p.featured,
      unpublished: !!p.unpublished,
      verdict: p.verdict || "",
    });
    setFormError("");
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  function cancelEdit() {
    setEditingId(null);
    setForm(EMPTY_FORM);
    setFormError("");
  }

  async function handleSubmit(e) {
    e.preventDefault();
    if (saving) return;
    setSaving(true);
    setFormError("");
    try {
      const url = editingId ? `/api/admin/faq/${editingId}` : "/api/admin/faq";
      const res = await fetch(url, {
        method: editingId ? "PUT" : "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      const data = await res.json();
      if (!res.ok) {
        setFormError(data.error || "Something went wrong.");
        return;
      }
      cancelEdit();
      load();
    } catch {
      setFormError("Couldn't reach the server.");
    } finally {
      setSaving(false);
    }
  }

  // Unpublish rather than delete: an auto-generated post that reads wrong
  // needs to come down immediately, but it's also evidence of what was being
  // asked. Hiding keeps the record.
  async function togglePublish(post) {
    const res = await fetch(`/api/admin/faq/${post.id}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        title: post.title,
        body: post.body,
        sourceLink: post.sourceLink || "",
        topicTag: post.topicTag || "",
        featured: !!post.featured,
        verdict: post.verdict || "",
        unpublished: !post.unpublished,
      }),
    });
    if (res.ok) load();
  }

  async function handleDelete(id) {
    if (!confirm("Delete this FAQ post? Unpublishing hides it without losing it.")) return;
    const res = await fetch(`/api/admin/faq/${id}`, { method: "DELETE" });
    if (res.ok) load();
  }

  const visible = (posts || []).filter((p) => {
    if (filter === "auto") return p.isAutoGenerated;
    if (filter === "manual") return !p.isAutoGenerated;
    if (filter === "hidden") return p.unpublished;
    return true;
  });

  const autoCount = (posts || []).filter((p) => p.isAutoGenerated && !p.unpublished).length;

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="font-display text-xl font-semibold sm:text-2xl">FAQ &amp; news</h1>
        <p className="mt-1 text-sm leading-relaxed text-muted">
          Manually written posts, plus auto-generated drafts from claims multiple sessions
          asked about recently — review those before they read as official.
        </p>
      </div>

      {autoCount > 0 && (
        <Card className="border-accent/40 bg-accent-softer">
          <p className="text-xs leading-relaxed">
            <strong className="text-accent">{autoCount}</strong> live post
            {autoCount === 1 ? " was" : "s were"} drafted automatically after enough distinct
            people asked the same thing. They&apos;re published and public — edit or unpublish
            any that read wrong.
          </p>
        </Card>
      )}

      <div className="lg:grid lg:grid-cols-[minmax(0,1fr)_minmax(0,1.2fr)] lg:items-start lg:gap-6">
        <Card raised className="lg:sticky lg:top-36">
          <SectionLabel tone="accent" className="mb-3">
            {editingId ? "Edit post" : "Add a post"}
          </SectionLabel>
          <form onSubmit={handleSubmit} className="flex flex-col gap-3">
            <input
              required
              placeholder="Title — phrase it as the question people ask"
              value={form.title}
              onChange={(e) => setForm({ ...form, title: e.target.value })}
              className="field"
            />
            <textarea
              required
              rows={5}
              placeholder="Answer body"
              value={form.body}
              onChange={(e) => setForm({ ...form, body: e.target.value })}
              className="field resize-y"
            />
            <div className="grid gap-3 sm:grid-cols-2">
              <input
                placeholder="Topic tag (optional)"
                value={form.topicTag}
                onChange={(e) => setForm({ ...form, topicTag: e.target.value })}
                className="field"
              />
              <input
                type="url"
                placeholder="Source link (optional)"
                value={form.sourceLink}
                onChange={(e) => setForm({ ...form, sourceLink: e.target.value })}
                className="field"
              />
            </div>

            <fieldset>
              <legend className="label-tracked mb-2 text-[10px] text-muted">
                Verdict (optional)
              </legend>
              <div className="flex flex-wrap gap-2">
                {VERDICTS.map((v) => (
                  <button
                    key={v}
                    type="button"
                    onClick={() =>
                      setForm({ ...form, verdict: form.verdict === v ? "" : v })
                    }
                    aria-pressed={form.verdict === v}
                    className={`label-tracked rounded-full border px-3 py-2 text-[10px] transition-colors ${
                      form.verdict === v
                        ? "border-accent bg-accent-soft text-accent"
                        : "border-border text-muted hover:border-border-strong hover:text-foreground"
                    }`}
                  >
                    {v}
                  </button>
                ))}
              </div>
            </fieldset>

            <label className="flex cursor-pointer items-start gap-3 rounded-2xl border border-border p-3">
              <input
                type="checkbox"
                checked={form.featured}
                onChange={(e) => setForm({ ...form, featured: e.target.checked })}
                className="mt-0.5 size-4 accent-[#1db876]"
              />
              <span className="text-xs leading-relaxed">
                <span className="label-tracked text-[10px] text-foreground">
                  Feature as trending
                </span>
                <span className="mt-0.5 block text-faint">
                  Spotlights this on the homepage feed without waiting for auto-clustering —
                  useful for a demo before there&apos;s real traffic.
                </span>
              </span>
            </label>

            <label className="flex cursor-pointer items-start gap-3 rounded-2xl border border-border p-3">
              <input
                type="checkbox"
                checked={form.unpublished}
                onChange={(e) => setForm({ ...form, unpublished: e.target.checked })}
                className="mt-0.5 size-4 accent-[#f5b400]"
              />
              <span className="text-xs leading-relaxed">
                <span className="label-tracked text-[10px] text-foreground">Unpublished</span>
                <span className="mt-0.5 block text-faint">
                  Hidden from the public FAQ and trending feed, but kept on record.
                </span>
              </span>
            </label>

            {formError && (
              <p className="text-xs text-danger" role="alert">
                {formError}
              </p>
            )}

            <div className="flex gap-2">
              <PillButton type="submit" disabled={saving}>
                {saving ? "Saving…" : editingId ? "Save changes" : "Add post"}
              </PillButton>
              {editingId && (
                <PillButton type="button" variant="outline" onClick={cancelEdit}>
                  Cancel
                </PillButton>
              )}
            </div>
          </form>
        </Card>

        <div className="mt-6 lg:mt-0">
          <div className="no-scrollbar mb-3 flex gap-2 overflow-x-auto pb-1">
            {FILTERS.map((f) => (
              <button
                key={f.key}
                type="button"
                onClick={() => setFilter(f.key)}
                aria-pressed={filter === f.key}
                className={`label-tracked shrink-0 rounded-full border px-3 py-1.5 text-[10px] transition-colors ${
                  filter === f.key
                    ? "border-accent bg-accent-soft text-accent"
                    : "border-border text-muted hover:border-border-strong hover:text-foreground"
                }`}
              >
                {f.label}
              </button>
            ))}
          </div>

          {error && <p className="text-danger">{error}</p>}
          {!posts && !error && <p className="text-muted">Loading…</p>}
          {posts && visible.length === 0 && (
            <Card className="text-center">
              <p className="text-sm text-muted">
                {posts.length === 0 ? "No posts yet." : "Nothing matches this filter."}
              </p>
            </Card>
          )}

          <div className="flex flex-col gap-2">
            {visible.map((p) => (
              <Card key={p.id} className={p.unpublished ? "opacity-60" : ""}>
                <div className="flex items-start justify-between gap-3">
                  <div className="min-w-0 flex-1">
                    <div className="mb-1 flex flex-wrap items-center gap-1.5">
                      {p.verdict && <VerdictBadge verdict={p.verdict} />}
                      {p.isAutoGenerated && (
                        <span
                          className="label-tracked rounded-full bg-accent-soft px-2 py-0.5 text-[9px] text-accent"
                          title={
                            p.clusterSize
                              ? `${p.clusterSize} distinct sessions asked about this`
                              : undefined
                          }
                        >
                          Auto-generated{p.clusterSize ? ` · ${p.clusterSize}` : ""}
                        </span>
                      )}
                      {p.featured && (
                        <span className="label-tracked rounded-full bg-caution-soft px-2 py-0.5 text-[9px] text-caution">
                          Trending
                        </span>
                      )}
                      {p.unpublished && (
                        <span className="label-tracked rounded-full bg-unverified-soft px-2 py-0.5 text-[9px] text-unverified">
                          Unpublished
                        </span>
                      )}
                    </div>
                    <p className="text-sm leading-snug font-medium">{p.title}</p>
                    <p className="mt-1 line-clamp-2 text-xs leading-relaxed text-muted">
                      {p.body}
                    </p>
                    {p.topicTag && (
                      <span className="label-tracked mt-2 inline-block text-[9px] text-faint">
                        #{p.topicTag}
                      </span>
                    )}
                  </div>

                  <div className="flex shrink-0 flex-col gap-1.5">
                    <button
                      onClick={() => startEdit(p)}
                      className="label-tracked text-[10px] text-accent hover:underline"
                    >
                      Edit
                    </button>
                    <button
                      onClick={() => togglePublish(p)}
                      className="label-tracked text-[10px] text-caution hover:underline"
                    >
                      {p.unpublished ? "Publish" : "Unpublish"}
                    </button>
                    <button
                      onClick={() => handleDelete(p.id)}
                      className="label-tracked text-[10px] text-danger hover:underline"
                    >
                      Delete
                    </button>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
