import { NextResponse } from "next/server";
import { getCollections } from "@/lib/mongodb";

// Escape regex metacharacters so a search term containing them (parens,
// plus signs, etc — common in claim text) can't produce an invalid regex
// or unintended matches.
function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Public FAQ listing — the searchable/filterable news+FAQ page.
export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const tag = searchParams.get("tag");
  const q = searchParams.get("q");

  try {
    const { faqPosts } = await getCollections();

    const filter = { unpublished: { $ne: true } };
    if (tag) filter.topicTag = tag.toLowerCase();
    if (q) {
      // Search the body as well as the title — a user searching "dengue"
      // shouldn't miss a post whose title is phrased as a question that
      // happens not to contain the word.
      const rx = { $regex: escapeRegex(q), $options: "i" };
      filter.$or = [{ title: rx }, { body: rx }, { topicTag: rx }];
    }

    const [posts, tags] = await Promise.all([
      faqPosts.find(filter).sort({ createdAt: -1 }).limit(100).toArray(),
      // Distinct tags across published posts, so the filter chips only ever
      // show topics that actually have entries behind them.
      faqPosts.distinct("topicTag", { unpublished: { $ne: true }, topicTag: { $ne: null } }),
    ]);

    return NextResponse.json({
      tags: tags.filter(Boolean).sort(),
      posts: posts.map((p) => ({
        id: p._id.toString(),
        title: p.title,
        body: p.body,
        sourceLink: p.sourceLink,
        topicTag: p.topicTag,
        isAutoGenerated: !!p.isAutoGenerated,
        verdict: p.verdict || null,
        riskLevel: p.riskLevel || null,
        clusterSize: p.clusterSize || null,
        createdAt: p.createdAt,
      })),
    });
  } catch (err) {
    console.error("[/api/faq] error:", err);
    return NextResponse.json({ error: "Something went wrong." }, { status: 500 });
  }
}
