import { NextResponse } from "next/server";
import { getCollections } from "@/lib/mongodb";

// Escape regex metacharacters so a search term containing them (parens,
// plus signs, etc — common in claim text) can't produce an invalid regex
// or unintended matches.
function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const tag = searchParams.get("tag");
  const q = searchParams.get("q");

  try {
    const { faqPosts } = await getCollections();
    const filter = {};
    if (tag) filter.topicTag = tag;
    if (q) filter.title = { $regex: escapeRegex(q), $options: "i" };

    const posts = await faqPosts.find(filter).sort({ createdAt: -1 }).limit(100).toArray();
    return NextResponse.json(
      posts.map((p) => ({
        id: p._id.toString(),
        title: p.title,
        body: p.body,
        sourceLink: p.sourceLink,
        topicTag: p.topicTag,
        isAutoGenerated: !!p.isAutoGenerated,
        verdict: p.verdict || null,
        createdAt: p.createdAt,
      }))
    );
  } catch (err) {
    console.error("[/api/faq] error:", err);
    return NextResponse.json({ error: "Something went wrong." }, { status: 500 });
  }
}
