import { NextResponse } from "next/server";
import { getCollections } from "@/lib/mongodb";
import { requireAdmin } from "@/lib/requireAdmin";
import { verdictToRiskLevel } from "@/lib/risk";
import { normalizeTags } from "@/lib/tags";
import { SUPPORTED_LANGUAGES } from "@/lib/i18n";

const VALID_VERDICTS = ["true", "false", "misleading", "unverified"];

// Admin listing includes everything (auto-generated drafts included) —
// the public /api/faq route is the filtered, published-facing view.
export async function GET(request) {
  const { admin, response } = requireAdmin(request);
  if (!admin) return response;

  try {
    const { faqPosts } = await getCollections();
    const list = await faqPosts.find({}).sort({ createdAt: -1 }).toArray();

    return NextResponse.json(
      list.map((p) => ({
        id: p._id.toString(),
        title: p.title,
        body: p.body,
        sourceLink: p.sourceLink,
        topicTag: p.topicTag,
        isAutoGenerated: !!p.isAutoGenerated,
        featured: !!p.featured,
        unpublished: !!p.unpublished,
        language: p.language || "en",
        verdict: p.verdict || null,
        riskLevel: p.riskLevel || null,
        clusterSize: p.clusterSize || null,
        clusterTotalSessions: p.clusterTotalSessions || null,
        clusterShare: typeof p.clusterShare === "number" ? p.clusterShare : null,
        createdAt: p.createdAt,
      }))
    );
  } catch (err) {
    console.error("[/api/admin/faq GET] error:", err);
    return NextResponse.json({ error: "Something went wrong." }, { status: 500 });
  }
}

export async function POST(request) {
  const { admin, response } = requireAdmin(request);
  if (!admin) return response;

  let body;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const title = typeof body.title === "string" ? body.title.trim() : "";
  const bodyText = typeof body.body === "string" ? body.body.trim() : "";
  const sourceLink = typeof body.sourceLink === "string" ? body.sourceLink.trim() : "";
  // Normalised through the same helper as source tags, so an admin typing
  // "Dengue" and an auto-generated "dengue" land in the same filter bucket.
  const topicTag = normalizeTags(body.topicTag)[0] || "";
  const featured = !!body.featured;
  const unpublished = !!body.unpublished;
  const verdict = VALID_VERDICTS.includes(body.verdict) ? body.verdict : null;
  // The language the admin actually wrote this entry in. Without it, an entry
  // typed in Malay is stored as English and /api/faq/translate treats it as
  // "already translated" — so it never renders in the reader's language.
  const language = SUPPORTED_LANGUAGES.includes(body.language) ? body.language : "en";

  if (!title || !bodyText) {
    return NextResponse.json({ error: "title and body are required" }, { status: 400 });
  }

  try {
    const { faqPosts } = await getCollections();
    const doc = {
      title,
      body: bodyText,
      sourceLink: sourceLink || null,
      topicTag: topicTag || null,
      isAutoGenerated: false,
      // Set by the admin on the form — see note above. Defaults to English.
      language,
      unpublished,
      // Lets an admin manually spotlight a known viral claim on the
      // homepage "Trending right now" feed, independent of the
      // auto-clustering signal (see /api/trending, lib/autoFaq.js).
      featured,
      verdict,
      riskLevel: verdict ? verdictToRiskLevel(verdict) : null,
      createdBy: admin.email,
      createdAt: new Date(),
    };
    const inserted = await faqPosts.insertOne(doc);
    return NextResponse.json(
      { id: inserted.insertedId.toString(), ...doc },
      { status: 201 }
    );
  } catch (err) {
    console.error("[/api/admin/faq POST] error:", err);
    return NextResponse.json({ error: "Something went wrong." }, { status: 500 });
  }
}
