import { NextResponse } from "next/server";
import { getCollections } from "@/lib/mongodb";
import { requireAdmin } from "@/lib/requireAdmin";

// Admin listing includes everything (auto-generated drafts included) —
// the public /api/faq route is the filtered, published-facing view.
export async function GET(request) {
  const { admin, response } = requireAdmin(request);
  if (!admin) return response;

  try {
    const { faqPosts } = await getCollections();
    const list = await faqPosts.find({}).sort({ createdAt: -1 }).toArray();

    return NextResponse.json(
      list.map((p) => ({
        id: p._id.toString(),
        title: p.title,
        body: p.body,
        sourceLink: p.sourceLink,
        topicTag: p.topicTag,
        isAutoGenerated: !!p.isAutoGenerated,
        createdAt: p.createdAt,
      }))
    );
  } catch (err) {
    console.error("[/api/admin/faq GET] error:", err);
    return NextResponse.json({ error: "Something went wrong." }, { status: 500 });
  }
}

export async function POST(request) {
  const { admin, response } = requireAdmin(request);
  if (!admin) return response;

  let body;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const title = typeof body.title === "string" ? body.title.trim() : "";
  const bodyText = typeof body.body === "string" ? body.body.trim() : "";
  const sourceLink = typeof body.sourceLink === "string" ? body.sourceLink.trim() : "";
  const topicTag = typeof body.topicTag === "string" ? body.topicTag.trim() : "";

  if (!title || !bodyText) {
    return NextResponse.json({ error: "title and body are required" }, { status: 400 });
  }

  try {
    const { faqPosts } = await getCollections();
    const doc = {
      title,
      body: bodyText,
      sourceLink: sourceLink || null,
      topicTag: topicTag || null,
      isAutoGenerated: false,
      createdBy: admin.email,
      createdAt: new Date(),
    };
    const inserted = await faqPosts.insertOne(doc);
    return NextResponse.json(
      { id: inserted.insertedId.toString(), ...doc },
      { status: 201 }
    );
  } catch (err) {
    console.error("[/api/admin/faq POST] error:", err);
    return NextResponse.json({ error: "Something went wrong." }, { status: 500 });
  }
}
