import { NextResponse } from "next/server";
import { ObjectId } from "mongodb";
import { getCollections } from "@/lib/mongodb";
import { requireAdmin } from "@/lib/requireAdmin";

export async function PUT(request, { params }) {
  const { admin, response } = requireAdmin(request);
  if (!admin) return response;

  const { id } = await params;
  if (!ObjectId.isValid(id)) {
    return NextResponse.json({ error: "Invalid id" }, { status: 400 });
  }

  let body;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const title = typeof body.title === "string" ? body.title.trim() : "";
  const bodyText = typeof body.body === "string" ? body.body.trim() : "";
  const sourceLink = typeof body.sourceLink === "string" ? body.sourceLink.trim() : "";
  const topicTag = typeof body.topicTag === "string" ? body.topicTag.trim() : "";

  if (!title || !bodyText) {
    return NextResponse.json({ error: "title and body are required" }, { status: 400 });
  }

  try {
    const { faqPosts } = await getCollections();
    const result = await faqPosts.findOneAndUpdate(
      { _id: new ObjectId(id) },
      {
        $set: {
          title,
          body: bodyText,
          sourceLink: sourceLink || null,
          topicTag: topicTag || null,
          updatedAt: new Date(),
          updatedBy: admin.email,
        },
      },
      { returnDocument: "after" }
    );

    const updated = result?.value || result;
    if (!updated) {
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }

    return NextResponse.json({
      id: updated._id.toString(),
      title: updated.title,
      body: updated.body,
      sourceLink: updated.sourceLink,
      topicTag: updated.topicTag,
      isAutoGenerated: !!updated.isAutoGenerated,
    });
  } catch (err) {
    console.error("[/api/admin/faq/[id] PUT] error:", err);
    return NextResponse.json({ error: "Something went wrong." }, { status: 500 });
  }
}

export async function DELETE(request, { params }) {
  const { admin, response } = requireAdmin(request);
  if (!admin) return response;

  const { id } = await params;
  if (!ObjectId.isValid(id)) {
    return NextResponse.json({ error: "Invalid id" }, { status: 400 });
  }

  try {
    const { faqPosts } = await getCollections();
    const result = await faqPosts.deleteOne({ _id: new ObjectId(id) });
    if (result.deletedCount === 0) {
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }
    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error("[/api/admin/faq/[id] DELETE] error:", err);
    return NextResponse.json({ error: "Something went wrong." }, { status: 500 });
  }
}
