import { NextResponse } from "next/server";
import { ObjectId } from "mongodb";
import { getCollections } from "@/lib/mongodb";
import { requireAdmin } from "@/lib/requireAdmin";
import { verdictToRiskLevel } from "@/lib/risk";
import { normalizeTags } from "@/lib/tags";
import { SUPPORTED_LANGUAGES } from "@/lib/i18n";

const VALID_VERDICTS = ["true", "false", "misleading", "unverified"];

export async function PUT(request, { params }) {
  const { admin, response } = requireAdmin(request);
  if (!admin) return response;

  const { id } = await params;
  if (!ObjectId.isValid(id)) {
    return NextResponse.json({ error: "Invalid id" }, { status: 400 });
  }

  let body;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const title = typeof body.title === "string" ? body.title.trim() : "";
  const bodyText = typeof body.body === "string" ? body.body.trim() : "";
  const sourceLink = typeof body.sourceLink === "string" ? body.sourceLink.trim() : "";
  const topicTag = normalizeTags(body.topicTag)[0] || "";
  const featured = !!body.featured;
  // Unpublishing hides a post from the public FAQ and the trending feed
  // without deleting it — the spec's "edit/unpublish an auto-generated post"
  // path, and safer than delete for something a human is reviewing.
  const unpublished = !!body.unpublished;
  const verdict = VALID_VERDICTS.includes(body.verdict) ? body.verdict : null;
  // The language this entry is written in. Correcting it (e.g. a post typed in
  // Malay that was stored as English) is the whole point of exposing it here,
  // so a wrong value can be fixed after the fact.
  const language = SUPPORTED_LANGUAGES.includes(body.language) ? body.language : "en";

  if (!title || !bodyText) {
    return NextResponse.json({ error: "title and body are required" }, { status: 400 });
  }

  try {
    const { faqPosts } = await getCollections();
    const existing = await faqPosts.findOne(
      { _id: new ObjectId(id) },
      { projection: { language: 1 } }
    );
    // Any cached translations were produced against the old source language, so
    // once that changes they're stale — drop them and let them be regenerated.
    const languageChanged = existing && (existing.language || "en") !== language;

    const result = await faqPosts.findOneAndUpdate(
      { _id: new ObjectId(id) },
      {
        $set: {
          title,
          body: bodyText,
          sourceLink: sourceLink || null,
          topicTag: topicTag || null,
          featured,
          unpublished,
          language,
          verdict,
          riskLevel: verdict ? verdictToRiskLevel(verdict) : null,
          updatedAt: new Date(),
          updatedBy: admin.email,
        },
        ...(languageChanged ? { $unset: { translations: "" } } : {}),
      },
      { returnDocument: "after" }
    );

    const updated = result?.value || result;
    if (!updated) {
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }

    return NextResponse.json({
      id: updated._id.toString(),
      title: updated.title,
      body: updated.body,
      sourceLink: updated.sourceLink,
      topicTag: updated.topicTag,
      isAutoGenerated: !!updated.isAutoGenerated,
      featured: !!updated.featured,
      unpublished: !!updated.unpublished,
      language: updated.language || "en",
      verdict: updated.verdict || null,
      riskLevel: updated.riskLevel || null,
    });
  } catch (err) {
    console.error("[/api/admin/faq/[id] PUT] error:", err);
    return NextResponse.json({ error: "Something went wrong." }, { status: 500 });
  }
}

export async function DELETE(request, { params }) {
  const { admin, response } = requireAdmin(request);
  if (!admin) return response;

  const { id } = await params;
  if (!ObjectId.isValid(id)) {
    return NextResponse.json({ error: "Invalid id" }, { status: 400 });
  }

  try {
    const { faqPosts } = await getCollections();
    const result = await faqPosts.deleteOne({ _id: new ObjectId(id) });
    if (result.deletedCount === 0) {
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }
    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error("[/api/admin/faq/[id] DELETE] error:", err);
    return NextResponse.json({ error: "Something went wrong." }, { status: 500 });
  }
}
