import { NextResponse } from "next/server";
import { getCollections } from "@/lib/mongodb";

// Public, unauthenticated — powers the homepage "Trending right now" feed.
//
// "Trending" here means one of two things:
//   1. Auto-generated FAQ posts (isAutoGenerated: true) — created when 5+
//      distinct sessions asked about the same claim within 24h (see
//      lib/autoFaq.js). This is a live signal derived from real usage,
//      no external social-media API required.
//   2. Admin-curated posts explicitly marked `featured: true` — lets an
//      admin manually spotlight a known viral topic (useful for a demo
//      before there's enough real traffic to trigger auto-clustering).
export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const limit = Math.min(parseInt(searchParams.get("limit") || "6", 10) || 6, 20);

  try {
    const { faqPosts } = await getCollections();
    const list = await faqPosts
      .find({ $or: [{ isAutoGenerated: true }, { featured: true }] })
      .sort({ createdAt: -1 })
      .limit(limit)
      .toArray();

    return NextResponse.json(
      list.map((p) => ({
        id: p._id.toString(),
        title: p.title,
        body: p.body,
        exampleText: p.exampleText || null,
        topicTag: p.topicTag,
        sourceLink: p.sourceLink,
        verdict: p.verdict || null,
        riskLevel: p.riskLevel || null,
        clusterSize: p.clusterSize || null,
        isAutoGenerated: !!p.isAutoGenerated,
        featured: !!p.featured,
        createdAt: p.createdAt,
      }))
    );
  } catch (err) {
    console.error("[/api/trending] error:", err);
    return NextResponse.json({ error: "Something went wrong." }, { status: 500 });
  }
}
